"""Allow guest orders, use status for cart vs paid

Revision ID: 7600d232c513
Revises: 645d5183ddb5
Create Date: 2025-11-09 13:09:58.959175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7600d232c513'
down_revision = '645d5183ddb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guest_cart',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=80), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('guest_cart', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_guest_cart_session_id'), ['session_id'], unique=False)

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('guest_cart', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_guest_cart_session_id'))

    op.drop_table('guest_cart')
    # ### end Alembic commands ###
